
project_id = "bzegjbtbwhgaqlvdudsh"

[api]
enabled = true
port = 54321
invoice_enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "https://api.supabase.io"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions]
[functions.generate-report]
verify_jwt = true
