
# This file contains configuration for the local development server.
project_id = "bzegjbtbwhgaqlvdudsh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions]
[functions.create-subscription-checkout]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = false
