// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzegjbtbwhgaqlvdudsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZWdqYnRid2hnYXFsdmR1ZHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTE5NzksImV4cCI6MjA2MDQyNzk3OX0.fDSiUf8Zk5sdkP0o0xdoIjEXQU9AxS3JZj-bskOBoHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);